[package]
name = "serde-xdr"
version = "0.1.0"
authors = ["Janito Vaqueiro Ferreira Filho <janito.vff@gmail.com>"]

[dependencies]
byteorder = "1.1"
error-chain = "0.11"
serde = "1.0"

[dev-dependencies]
ordered-float = "0.5"
serde_derive = "1.0"
